### ISSUE TITLE
Class 'fkooman\Config\Config' not found 

### ISSUE THREAD

**Issue by madsi1m** [OpenConextApps/php-voot-provider#7]
Hi, I keep getting this error when i try php bin/addUsers.php and php bin/BackendTest.php fkooman

I have tried it with release version and git/composer.

my vendor directory seems to have the files:
ls -l vendor/fkooman/config/src/fkooman/Config
total 24
-rw-r--r-- 1 root root  913 Nov  9  2015 ArrayReader.php
-rw-r--r-- 1 root root 1315 Nov  9  2015 IniFile.php
-rw-r--r-- 1 root root  249 Nov  9  2015 ReaderInterface.php
-rw-r--r-- 1 root root 3670 Nov  9  2015 Reader.php
-rw-r--r-- 1 root root  263 Nov  9  2015 WriterInterface.php
-rw-r--r-- 1 root root 1528 Nov  9  2015 YamlFile.php

Am i missing something?

**Comment by fkooman** [comment]
https://github.com/fkooman/php-voot-provider/commit/87c69a8d0c722f59b3497bda8bf143face709e4a

**Comment by fkooman** [comment]
I created a PR fixing this and possible future issues with missing/broken external dependencies:

https://github.com/OpenConextApps/php-voot-provider/pull/8

**Comment by thijskh** [comment]
Thanks @fkooman!

@madsi1m Can you confirm that it works for you now? Then I'll create a new release.

**Comment by madsi1m** [comment]
Hi, yes latest git code seems to work now. Thanks for the fix.
